const config = {
    JWT_SECRET: process.env.JWT_SECRET,
    HASH_SALT: process.env.HASH_SALT,
    DB_SSL: process.env.DB_SSL,
    JWT_ACCESS_TOKEN_LIFE_TIME: process.env.JWT_ACCESS_TOKEN_LIFE_TIME,
    JWT_REFRESH_TOKEN_LIFE_TIME: process.env.JWT_REFRESH_TOKEN_LIFE_TIME,
    FORGET_PASSWORD_JWT_SECRET: process.env.FORGET_PASSWORD_JWT_SECRET,
    JWT_INVITATION_TOKEN_LIFE_TIME: process.env.JWT_INVITATION_TOKEN_LIFE_TIME,
    INVITATION_JWT_SECRET: process.env.INVITATION_JWT_SECRET,
    AUTHORIZE: {
      SECRET: process.env.AUTHORIZE_SECRET,
      TOKEN_SECRET: process.env.AUTHORIZE_TOKEN_SECRET,
      ALGORITHM: process.env.AUTHORIZE_ALGORITHM,
      ENCODING_TYPE_ONE: process.env.AUTHORIZE_ENCODING_TYPE_ONE,
      ENCODING_TYPE_TWO: process.env.AUTHORIZE_ENCODING_TYPE_TWO,
    },
  };
  
  export default config;
  